<?php 
    session_start();
    include('entete.php'); ?>


    <!-- Page Content -->

    <div class="FemmeContenu">
	
	<h1>Femme</h1>

<div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Nom du produit</h3>
                        <p>Calibre, poids, chargeur</p>
                        <p>
                            <a href="#" class="btn btn-primary">Acheter</a> <a href="#" class="btn btn-default">Infos</a>
                        </p>
                    </div>
                </div>
            </div>

<div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Nom du produit</h3>
                        <p>Calibre, poids, chargeur</p>
                        <p>
                            <a href="#" class="btn btn-primary">Acheter</a> <a href="#" class="btn btn-default">Infos</a>
                        </p>
                    </div>
                </div>
            </div>

<div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Nom du produit</h3>
                        <p>Calibre, poids, chargeur</p>
                        <p>
                            <a href="#" class="btn btn-primary">Acheter</a> <a href="#" class="btn btn-default">Infos</a>
                        </p>
                    </div>
                </div>
            </div>

<div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Nom du produit</h3>
                        <p>Calibre, poids, chargeur</p>
                        <p>
                            <a href="#" class="btn btn-primary">Acheter</a> <a href="#" class="btn btn-default">Infos</a>
                        </p>
                    </div>
                </div>
            </div>


</body>
</html>
